name: Test

on:
  push:
    paths:
      - "src/contracts/**"
      - "test/**"
  pull_request:
    paths:
      - "src/contracts/**"
      - "test/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          version: latest

      - name: Install Foundry dependencies
        run: forge install

      - name: Install Bun dependencies
        run: bun install --no-cache

      - name: Run tests
        run: forge test -vv
